# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: istio
#   name: ingress
# spec:
#   rules:
#   - host: 10.103.253.183.xip.io
#     http:
#       paths:
#       - path: /*
#         backend:
#           serviceName: wordpress
#           servicePort: 8000
#---
  
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: wordpress
  spec:
    selector:
      istio: ingressgateway
    servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      - 10.103.253.183.xip.io
---
  apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: wordpress
  spec:
    hosts:
    - 10.103.253.183.xip.io
    gateways:
    - wordpress
    http:  
    - route:
      - destination:
          host: wordpress
          port:
            number: 8000            
   
